In [1]:
!ls

Hmatrix-256-16.csv Untitled.ipynb


In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Hmatrix-256-16.csv')

In [4]:
df.head()

UI  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  15.6  15.7  15.8  15.9  \
0  DQ  0    1    2    3    4    5    6    7    8  ...     6     7     8     9   
1  P0  1    0    0    0    1    1    1    1    1  ...     0     0     0     1   
2  P1  0    1    0    0    0    1    0    1    0  ...     1     0     1     0   
3  P2  0    1    0    1    0    1    0    0    0  ...     0     0     0     1   
4  P3  1    0    1    0    1    0    1    0    0  ...     0     0     1     1   

   15.10  15.11  15.12  15.13  15.14  15.15  
0     10     11     12     13     14     15  
1      0      0      0      1      0      0  
2      0      0      1      0      0      0  
3      0      0      1      1      1      0  
4      0      1      1      0      0      0  

[5 rows x 257 columns]

In [10]:
#Drop first row
df.drop(df.index[0],inplace=True)

In [11]:
#Drop first column
df.drop(df.columns[0],axis=1,inplace=True)

In [12]:
df

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  15.6  15.7  15.8  \
1   1    0    0    0    1    1    1    1    1    0  ...     0     0     0   
2   0    1    0    0    0    1    0    1    0    1  ...     1     0     1   
3   0    1    0    1    0    1    0    0    0    1  ...     0     0     0   
4   1    0    1    0    1    0    1    0    0    1  ...     0     0     1   
5   0    0    1    1    1    1    1    0    1    1  ...     0     0     0   
6   0    0    1    1    0    0    0    1    1    0  ...     1     1     1   
7   0    1    1    1    0    0    1    0    1    1  ...     0     0     0   
8   0    0    1    0    0    1    1    1    1    0  ...     1     1     1   
9   1    1    1    0    0    0    1    1    0    1  ...     0     0     0   
10  1    1    0    1    0    0    0    0    1    1  ...     0     0     0   
11  1    1    1    0    0    1    1    0    1    1  ...     0     0     0   
12  1    0    0    0    1    0    1    0    0    0  ...     0     1     0   
13  0    0    1    1    1    0    0    0    0    1  ...     0     0     1   
14  0    1    0    1    1    1    1    1    0    0  ...     0     1     0   
15  1    1    1    0    1    0    0    0    0    0  ...     1     0     0   
16  0    1    0    0    0    0    0    1    0    0  ...     1     1     0   

    15.9  15.10  15.11  15.12  15.13  15.14  15.15  
1      1      0      0      0      1      0      0  
2      0      0      0      1      0      0      0  
3      1      0      0      1      1      1      0  
4      1      0      1      1      0      0      0  
5      0      0      0      0      1      0      0  
6      1      0      1      0      0      0      1  
7      0      0      0      1      0      0      0  
8      0      0      0      0      0      0      1  
9      0      1      0      0      0      0      0  
10     1      1      0      0      0      1      0  
11     0      1      1      0      0      0      1  
12     0      1      0      0      0      1      1  
13     0      0      0      0      0      0      1  
14     0      0      1      0      0      1      0  
15     0      0      1      1      1      0      0  
16     0      1      0      0      1      1      0  

[16 rows x 256 columns]

In [45]:
H = df.to_numpy(dtype=np.int8)

In [46]:
H

array([[1, 0, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 1, 0],
       ...,
       [0, 1, 0, ..., 0, 1, 0],
       [1, 1, 1, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 1, 0]], dtype=int8)

In [475]:
#Generate Checksum
for i in range(H.shape[0]):
    print(f"CHK[{i}] = ",end="")
    for j in range(H.shape[1]):
        if H[i,j]:
            print(f"IN[{j}] ^ ",end="")
    print(" 1'b0 ;")

CHK[0] = IN[0] ^ IN[4] ^ IN[5] ^ IN[6] ^ IN[7] ^ IN[8] ^ IN[11] ^ IN[13] ^ IN[14] ^ IN[16] ^ IN[18] ^ IN[21] ^ IN[25] ^ IN[26] ^ IN[27] ^ IN[28] ^ IN[31] ^ IN[32] ^ IN[33] ^ IN[34] ^ IN[36] ^ IN[37] ^ IN[38] ^ IN[39] ^ IN[40] ^ IN[44] ^ IN[45] ^ IN[47] ^ IN[51] ^ IN[55] ^ IN[59] ^ IN[60] ^ IN[61] ^ IN[64] ^ IN[66] ^ IN[69] ^ IN[70] ^ IN[72] ^ IN[73] ^ IN[75] ^ IN[77] ^ IN[81] ^ IN[83] ^ IN[85] ^ IN[87] ^ IN[88] ^ IN[92] ^ IN[96] ^ IN[97] ^ IN[102] ^ IN[103] ^ IN[106] ^ IN[107] ^ IN[108] ^ IN[109] ^ IN[113] ^ IN[114] ^ IN[115] ^ IN[116] ^ IN[121] ^ IN[122] ^ IN[124] ^ IN[127] ^ IN[128] ^ IN[129] ^ IN[130] ^ IN[131] ^ IN[133] ^ IN[135] ^ IN[136] ^ IN[138] ^ IN[140] ^ IN[144] ^ IN[146] ^ IN[147] ^ IN[153] ^ IN[154] ^ IN[156] ^ IN[158] ^ IN[159] ^ IN[164] ^ IN[167] ^ IN[175] ^ IN[177] ^ IN[181] ^ IN[186] ^ IN[187] ^ IN[189] ^ IN[194] ^ IN[200] ^ IN[202] ^ IN[205] ^ IN[211] ^ IN[212] ^ IN[217] ^ IN[220] ^ IN[222] ^ IN[225] ^ IN[231] ^ IN[234] ^ IN[236] ^ IN[241] ^ IN[242] ^ IN[243] ^ IN[244

In [474]:
#Generate Syndrome
for i in range(H.shape[0]):
    print(f"SYN[{i}] = ",end="")
    for j in range(H.shape[1]):
        if H[i,j]:
            print(f"IN[{j}] ^ ",end="")
    print(f"CHK[{i}];")

SYN[0] = IN[0] ^ IN[4] ^ IN[5] ^ IN[6] ^ IN[7] ^ IN[8] ^ IN[11] ^ IN[13] ^ IN[14] ^ IN[16] ^ IN[18] ^ IN[21] ^ IN[25] ^ IN[26] ^ IN[27] ^ IN[28] ^ IN[31] ^ IN[32] ^ IN[33] ^ IN[34] ^ IN[36] ^ IN[37] ^ IN[38] ^ IN[39] ^ IN[40] ^ IN[44] ^ IN[45] ^ IN[47] ^ IN[51] ^ IN[55] ^ IN[59] ^ IN[60] ^ IN[61] ^ IN[64] ^ IN[66] ^ IN[69] ^ IN[70] ^ IN[72] ^ IN[73] ^ IN[75] ^ IN[77] ^ IN[81] ^ IN[83] ^ IN[85] ^ IN[87] ^ IN[88] ^ IN[92] ^ IN[96] ^ IN[97] ^ IN[102] ^ IN[103] ^ IN[106] ^ IN[107] ^ IN[108] ^ IN[109] ^ IN[113] ^ IN[114] ^ IN[115] ^ IN[116] ^ IN[121] ^ IN[122] ^ IN[124] ^ IN[127] ^ IN[128] ^ IN[129] ^ IN[130] ^ IN[131] ^ IN[133] ^ IN[135] ^ IN[136] ^ IN[138] ^ IN[140] ^ IN[144] ^ IN[146] ^ IN[147] ^ IN[153] ^ IN[154] ^ IN[156] ^ IN[158] ^ IN[159] ^ IN[164] ^ IN[167] ^ IN[175] ^ IN[177] ^ IN[181] ^ IN[186] ^ IN[187] ^ IN[189] ^ IN[194] ^ IN[200] ^ IN[202] ^ IN[205] ^ IN[211] ^ IN[212] ^ IN[217] ^ IN[220] ^ IN[222] ^ IN[225] ^ IN[231] ^ IN[234] ^ IN[236] ^ IN[241] ^ IN[242] ^ IN[243] ^ IN[244

In [476]:
def get_random_vector(size):
    return np.random.randint(0,2,size,dtype=np.int8)

def compute_chksum(a,H):
    chksum = np.zeros(H.shape[0],dtype=np.int8)
    for i in range(0,H.shape[0]):
        for j in range(0,H.shape[1]):
            if H[i,j]:
                chksum[i] = chksum[i] ^ a[j]
    return chksum

def compute_syndrome_given_checksum(a,chk,H):
    syn = np.zeros(H.shape[0],dtype=np.int8)
    for i in range(0,H.shape[0]):
        syn[i] = chk[i]
        for j in range(0,H.shape[1]):
            if H[i,j]:
                syn[i] = syn[i] ^ a[j]
    return syn

def compute_syndrome(enc,H):
    a = enc[0:H.shape[1]]
    chk = enc[H.shape[1]:]
    return compute_syndrome_given_checksum(a,chk,H)

def flip(a,posn):
    if a[posn]:
        a[posn] = 0
    else:
        a[posn] = 1
    return a

def concat(a,chk):
    return np.concatenate((a,chk))

def correction_hash():
    chash = {}
    for posn in range(0,272):
        a = get_random_vector(256)
        chk = compute_chksum(a,H)
        dec_in = concat(a,chk)
        dec_err = flip(dec_in,posn)
        syn = compute_syndrome(dec_err,H)
        key = ''.join(map(str,syn))
        chash[key] = posn
    return chash

def correct(enc,chash):
    syn = compute_syndrome(enc,H)
    key = ''.join(map(str,syn))
    posn = chash[key]
    return flip(enc,posn)


In [455]:
a = get_random_vector(256)
print(a)

[0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 0 1 0 1 1 1 0 1 1 1 1 0 0 1 0 1 0 1 0 0 0 1 1 1 1 0 0 1 0 1 0 0 1 1 0
 1 0 0 1 1 0 0 1 1 0 0 1 0 1 0 0 1 1 0 0 1 1 0 0 1 0 0 0 0 1 1 1 1 1 1 0 0
 0 0 1 1 0 1 0 1 0 1 1 1 0 0 1 1 0 0 0 0 0 1 1 0 1 1 1 0 1 0 0 0 0 0 0 0 1
 0 1 1 1 1 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 1 1 0 1 0 1 0 0 0 1 1 1 0 0 0
 1 1 1 0 1 1 0 0 1 0 0 1 1 1 0 0 1 0 1 1 0 1 1 1 0 1 1 0 1 1 0 1 1 0 0 0 1
 0 0 0 0 0 1 0 1 1 1 1 0 1 0 0 1 1 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0]


In [456]:
chk = compute_chksum(a,H)
print(chk)

[1 1 0 1 1 1 0 1 1 1 0 0 0 0 1 0]


In [457]:
enc = concat(a,chk)
print(enc)

[0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 0 1 0 1 1 1 0 1 1 1 1 0 0 1 0 1 0 1 0 0 0 1 1 1 1 0 0 1 0 1 0 0 1 1 0
 1 0 0 1 1 0 0 1 1 0 0 1 0 1 0 0 1 1 0 0 1 1 0 0 1 0 0 0 0 1 1 1 1 1 1 0 0
 0 0 1 1 0 1 0 1 0 1 1 1 0 0 1 1 0 0 0 0 0 1 1 0 1 1 1 0 1 0 0 0 0 0 0 0 1
 0 1 1 1 1 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 1 1 0 1 0 1 0 0 0 1 1 1 0 0 0
 1 1 1 0 1 1 0 0 1 0 0 1 1 1 0 0 1 0 1 1 0 1 1 1 0 1 1 0 1 1 0 1 1 0 0 0 1
 0 0 0 0 0 1 0 1 1 1 1 0 1 0 0 1 1 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0
 1 1 1 0 1 1 1 0 0 0 0 1 0]


In [458]:
enc = flip(enc,0)

In [459]:
syn = compute_syndrome_given_checksum(a,chk,H)
print(syn)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [460]:
syn = compute_syndrome(enc,H)
print(syn)

[1 0 0 1 0 0 0 0 1 1 1 1 0 0 1 0]


In [461]:
a = get_random_vector(256)
print(np.sum(a))
chk = compute_chksum(a,H)
enc = concat(a,chk)
enc = flip(enc,255)
syn = compute_syndrome(enc,H)
print(syn)

124
[0 0 0 0 0 1 0 1 0 0 1 1 1 0 0 0]


In [477]:
chash = correction_hash()

In [466]:
for posn in range(1,272):
    a = get_random_vector(256)
    chk = compute_chksum(a,H)
    enc = concat(a,chk)
    enc = flip(enc,posn)
    dec_out = correct(enc,chash)
    check_correction = np.all(dec_out == concat(a,chk))
    assert check_correction , f"flip {posn}: {check_correction}"

In [478]:
chash

{'1001000011110010': 0,
 '0110001011100111': 1,
 '0001111110101010': 2,
 '0010111001001100': 3,
 '1001100000011110': 4,
 '1110100100100100': 5,
 '1001101110110100': 6,
 '1100010110000101': 7,
 '1000111101100000': 8,
 '0111101011101000': 9,
 '0011001110110000': 10,
 '1101101000111001': 11,
 '0000100110101011': 12,
 '1001110001000101': 13,
 '1011010100100100': 14,
 '0001011101011011': 15,
 '1011100000100000': 16,
 '0100010011110100': 17,
 '1110000100001101': 18,
 '0101101101111000': 19,
 '0000011010001111': 20,
 '1101101010010000': 21,
 '0000101100110000': 22,
 '0110100101101101': 23,
 '0000111111100101': 24,
 '1001010010100011': 25,
 '1001000111010001': 26,
 '1110110110110000': 27,
 '1001011101111000': 28,
 '0001101000101110': 29,
 '0110111011010100': 30,
 '1110010101110100': 31,
 '1101100001011011': 32,
 '1000000001100110': 33,
 '1001100101110000': 34,
 '0001010100111111': 35,
 '1000010000110001': 36,
 '1001011100010010': 37,
 '1110011110000011': 38,
 '1110111011001101': 39,
 '11000100

In [482]:
#Generate verilog case from chash
#Verilog bit vector has bit 0 to the right, so reverse key
#LOC is a mask that will flip the appropriate bit via XOR
#This assumes the CHECKSUM is towards the MSB of the 272 bit decoder input
for value,key, in enumerate(chash):
    reverse_key = key[::-1]
    print(f"16'b{reverse_key} : LOC = 272'd1 << {value} ;")

16'b0100111100001001 : LOC = 272'd1 << 0 ;
16'b1110011101000110 : LOC = 272'd1 << 1 ;
16'b0101010111111000 : LOC = 272'd1 << 2 ;
16'b0011001001110100 : LOC = 272'd1 << 3 ;
16'b0111100000011001 : LOC = 272'd1 << 4 ;
16'b0010010010010111 : LOC = 272'd1 << 5 ;
16'b0010110111011001 : LOC = 272'd1 << 6 ;
16'b1010000110100011 : LOC = 272'd1 << 7 ;
16'b0000011011110001 : LOC = 272'd1 << 8 ;
16'b0001011101011110 : LOC = 272'd1 << 9 ;
16'b0000110111001100 : LOC = 272'd1 << 10 ;
16'b1001110001011011 : LOC = 272'd1 << 11 ;
16'b1101010110010000 : LOC = 272'd1 << 12 ;
16'b1010001000111001 : LOC = 272'd1 << 13 ;
16'b0010010010101101 : LOC = 272'd1 << 14 ;
16'b1101101011101000 : LOC = 272'd1 << 15 ;
16'b0000010000011101 : LOC = 272'd1 << 16 ;
16'b0010111100100010 : LOC = 272'd1 << 17 ;
16'b1011000010000111 : LOC = 272'd1 << 18 ;
16'b0001111011011010 : LOC = 272'd1 << 19 ;
16'b1111000101100000 : LOC = 272'd1 << 20 ;
16'b0000100101011011 : LOC = 272'd1 << 21 ;
16'b0000110011010000 : LOC = 272'd1 << 22 